version: 2

defaults: &defaults
  environment:
     CACHE_VERSION: 1.0
  working_directory: ~/repo

  steps:
    - checkout

    - run:
        name: Cache env var workaround
        command: echo "$CACHE_VERSION" > _tmp_file

    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "_tmp_file" }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-{{ checksum "_tmp_file" }}-

    - run:
        name: Install elm globally
        command: yarn global add elm

    - run:
        name: Install and bootstrap packages
        command: yarn install --frozen-lockfile --ignore-engines

    - run:
        name: Run tests
        command: yarn test --runInBand --coverage

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "_tmp_file" }}-{{ checksum "yarn.lock" }}

    - persist_to_workspace:
        root: ~/repo
        paths: .

jobs:
  test-node8:
    <<: *defaults
    docker:
      - image: circleci/node:8
  test-node10:
    <<: *defaults
    docker:
      - image: circleci/node:10
  test-node11:
    <<: *defaults
    docker:
      - image: circleci/node:11
  test-node12:
    <<: *defaults
    docker:
      - image: circleci/node:12


workflows:
  version: 2
  test-deploy:
    jobs:
      - test-node8
      - test-node10
      - test-node11
      - test-node12
