name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build, test, Publish
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: Potentially save npm token
        run: |
          ([[ ! -z ${{ secrets.NPM_TOKEN }} ]] && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc) || echo "Did not write npm token"
      - name: Potentially publish finch to npm
        run: |
          if \
            [[ $(git describe --exact-match 2> /dev/null || :) =~ -finch ]]; \
          then
            yarn run lerna publish from-git --npm-tag finch --yes
          else
            echo "Did not publish finch"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Potentially publish canary to npm
        run: |
          if \
            [[ $(git describe --exact-match 2> /dev/null || :) =~ -canary ]]; \
          then
            yarn run lerna publish from-git --npm-tag canary --yes
          else
            echo "Did not publish canary"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Potentially publish stable to npm
        run: |
          if \
            [[ ! $(git describe --exact-match 2> /dev/null || :) =~ -canary|-finch ]]; \
          then
            yarn run lerna publish from-git --yes
          else
            echo "Did not publish"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
