name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build, test, Publish
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          always-auth: 'true'
      - run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: Read npm token from env
        run: |
          cp $NPM_CONFIG_USERCONFIG  ~/.npmrc
      - name: Potentially publish alpha to npm
        run: |
          if \
            [[ $(git describe --exact-match 2> /dev/null || :) =~ -alpha ]]; \
          then
            yarn publish-to-npm --tag alpha
          else
            echo "Did not publish alpha"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Potentially publish canary to npm
        run: |
          if \
            [[ $(git describe --exact-match 2> /dev/null || :) =~ -canary ]]; \
          then
            yarn publish-to-npm --tag canary
          else
            echo "Did not publish canary"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Potentially publish stable to npm
        run: |
          if \
            [[ ! $(git describe --exact-match 2> /dev/null || :) =~ -canary|-alpha ]]; \
          then
            yarn publish-to-npm
          else
            echo "Did not publish"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
